# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12458569fd0d30a92a4a1e6ba017a8bd634a7e6907f5a302cffebe5baff915695b1301b3660049c5f8422375ed56ba55b7c82c3e067223c17e0eb9e2c485a467

test:
  secret_key_base: 6ba5cf73f4a0b28c1c55b591ceaa5a04c1cfe37e3483ee1ad71bd81e0a384f28c267aad1b9c646aeb94a1ecd2befe819645289a107e74bff3cc5896303ff209d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
